### PR TITLE
Added support for google test running

### PR DESCRIPTION
**Pull request by 333fred**
This commit adds support for building and running the test suites on both Linux and Windows. To build all possible components and run the tests, run grade build. To just build all test-relevant components, run gradle :test:build. Note that on Windows, two tests are currently failing (they pass on my Linux machine):
[  FAILED  ] StorageTestsPersistent/StorageTestPersistent.SavePersistent/0, where GetParam() = false
[  FAILED  ] StorageTestsPersistent/StorageTestPersistent.SavePersistent/1, where GetParam() = true

### CODE REVIEW

**Comment by 333fred** [comment]
The important files to look at the new .gradle files. I've created a project for gmock/gtest, and a project for the tests proper.

**Comment by PeterJohnson** [comment]
Do we really need to bring all of these files into the source tree?  For example, there are two copies of gtest.h, one in gmock/fused-src and one in gtest/fused-src.  And we are never going to use the autoconf bits, only cmake or gradle.

**Comment by 333fred** [comment]
I've removed everything I feel comfortable with, removing almost 100 files. Let me know if there's anything else you think I can remove.

**Comment by PeterJohnson** [comment]
Merged with some further reductions and cmake integration as well.

**Pull request closed without merging**
