### PR TITLE
Switches AppVeyor to use same build for 32 and 64 bit java tests

### PR DESCRIPTION
**Pull request by ThadHouse**

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
What failed here?

**Comment by ThadHouse** [comment]
It looks like it just froze. I've seen that happen before randomly. I'll rebase and let it test again.

**Comment by ThadHouse** [comment]
So it does look like it was just a random crash. This definitely would be a nice fix, because right now AppVeyor runs 4 builds

**Comment by JLLeitschuh** [comment]
LGTM!

**Pull request merged**
