### PR TITLE
Malloc checks

### PR DESCRIPTION
**Pull request by XavilPergis**
I just added some checks for null pointers where they are appropriate.

### CODE REVIEW

**Comment by XavilPergis** [comment]
Whoops, I forgot some nots!

**Comment by PeterJohnson** [comment]
Can you change this to call std::terminate (http://en.cppreference.com/w/cpp/error/terminate) instead of exit?

**Comment by JLLeitschuh** [comment]
Include a message please.
Another potential, possibly simpler solution, is to create a common wrapper around malloc that will automatically call `terminate` so that this logic doesn't need to be added at every call site?

**Comment by PeterJohnson** [comment]
Superseded by wpilibsuite/allwpilib#1023.

**Pull request closed without merging**
