### PR TITLE
Distribute shared library .debug files.

### PR DESCRIPTION
**Pull request by PeterJohnson**

### CODE REVIEW

**Comment by PeterJohnson** [comment]
@333fred

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
Looks like travis did that oh hey, why don't I just rebuild this again even though it build successfully thing. https://ci.appveyor.com/project/frcjenkins/ntcore/build/dist-debug%20270/job/47m80yp7e0axiak4#L1189
@JLLeitschuh, any ideas on this?

**Comment by 333fred** [comment]
Or how we can trigger appveyor to rebuild?

**Comment by PeterJohnson** [comment]
Well, the appveyor PR build succeeded so it appears to be just an appveyor glitch on the branch build.  I'm going to go ahead and merge this.

**Pull request merged**
