### PR TITLE
Updated Gradle to 4.0.1

### PR DESCRIPTION
**Pull request by calcmogul**

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
This looks good.
I would use the full version of gradle instead but that's just me because I do a lot of gradle build development and I like having the docs downloaded too.
Example:
https://github.com/wpilibsuite/allwpilib/blob/master/build.gradle#L67-L70

**Review by JLLeitschuh — APPROVED** [review]

**Comment by PeterJohnson** [comment]
There's a major build system update that will be PR'ed soon, so this is OBE.

**Comment by JLLeitschuh** [comment]
"OBE"?

**Comment by calcmogul** [comment]
Obsoleted By Events.

**Pull request closed without merging**
