### PR TITLE
Connect to server in parallel rather than doing round-robin.

### PR DESCRIPTION
**Pull request by PeterJohnson**
This substantially speeds up client connection times.

### CODE REVIEW

**Comment by PeterJohnson** [comment]
@frcjenkins retest this please

**Comment by ThadHouse** [comment]
@frcjenkins retest this please

**Comment by ThadHouse** [comment]
@frcjenkins retest this please

**Comment by ThadHouse** [comment]
@frcjenkins retest this please

**Comment by ThadHouse** [comment]
@frcjenkins retest this please

**Pull request merged**
