### PR TITLE
added checks for compiler flags

### PR DESCRIPTION
**Pull request by PeterMitrano**
Stole this trick from gazebo, basically checks if a flag exists by test-compiling it, and adds it if it works. Be careful though--/Wall on windows is a nightmare...

### CODE REVIEW

**Comment by PeterJohnson** [comment]
Hmm, would it be better just to do if(MSVC) and define MSVC-specific flags?

**Comment by PeterMitrano** [comment]
It might be, but I happened to have this open from gazebo so I thought I'd
offer.

**Comment by PeterJohnson** [comment]
The current flags work on both GCC and clang.  What flags are you using on MSVC?

**Comment by PeterMitrano** [comment]
Updated with MSVC specific flags. the C++ 11 that it has is enabled default, and Wall/Wextra are a way too verbose for my tastes.

**Comment by PeterJohnson** [comment]
Merged modified and squashed version as 9f728b8

**Comment by PeterMitrano** [comment]
Just tried compiling WPILib Sim stuff with vc 2015...not immediately successful. I know it might be annoying, but can we settle for 2013? I'm worried it might require rebuilding gazebo and it's dependencies with msvc 2015.

**Pull request closed without merging**
