### PR TITLE
Add JSON support library

### PR DESCRIPTION
**Pull request by PeterJohnson**
This is a modified version of https://github.com/nlohmann/json.

It's been moved into the wpi namespace as many of the changes are not
compatible.  The amount of template code has been significantly reduced,
enabling many functions to be moved out-of-line, and for the result to
build on older compiler versions (in particular GCC 4.8).

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Legally you need to ensure that you include a copy of the `LICENSE.MIT`somewhere as we are vendoring this library. I don't think that just having the headers in the files is enough.

**Comment by PeterJohnson** [comment]
There shouldn't be a need for that.  The entirety of the MIT license is contained in the header (unlike e.g. the GPL, it's a very short license).  Or are you talking about when we distribute binaries since there's both header and non-header components?

**Comment by JLLeitschuh** [comment]
Yea, pretty much. Making sure you distribute the binaries with it

**Comment by PeterJohnson** [comment]
@frcjenkins retest this please

**Comment by PeterJohnson** [comment]
@frcjenkins retest this please

**Comment by AustinShalit** [comment]
@frcjenkins retest this please

**Comment by AustinShalit** [comment]
@frcjenkins retest this please

**Comment by PeterJohnson** [comment]
Closing in favor of wpilibsuite/wpiutil#5

**Pull request closed without merging**
