### PR TITLE
Fixed Gradle build to actually export proper functions

### PR DESCRIPTION
**Pull request by 333fred**
I forgot to set the linker to have the .defs file, and set it on just the compiler. This fixes that. It also fixes the incorrect spelling in the ntcore.defs file.

### CODE REVIEW

**Comment by PeterJohnson** [comment]
Should the /DEF flag be removed from the compiler line? (e.g. does it do anything there?)

**Comment by 333fred** [comment]
Should fix #13.

**Comment by PeterJohnson** [comment]
This change also changes the exportedHeaders to include everything in the src directory.  I'm not sure this is desirable?

**Comment by 333fred** [comment]
Updated. Those both were from the plane, I forgot to remove them from the final commit.

**Pull request merged**
